services:
  db:
    image: 'postgres:15-alpine'
    environment:
      - 'POSTGRES_DB=ecommerce_db'
      - 'POSTGRES_PASSWORD=123'
      - 'POSTGRES_USER=arthur'
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - 'db'
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: arthur
      SPRING_DATASOURCE_PASSWORD: 123
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/ecommerce_db

volumes:
  dbdata: